details:
  namespace: opsta-uat
  image: bigdev2000/details
  tag: uat
  replicas: 1
  imagePullSecrets: default-token-r2ttf
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: details.uat.big-bookinfo.opsta.in.th
  path: "/details(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  COMMIT_ID: CHANGE_ME